name: Create GitHub release

# Creates a release based on the Relay release requirements.
# 
# This action will generate a GitHub Release using the given source branch. It
# will also generate a new entry in the GitHub Release page and a new tag.

on: 
  workflow_call:
    inputs:
      release-name:
        description: 'Name of the release (defaults to the source branch name)'
        required: false
        type: string

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          fetch-depth: 0
          ref: ${{ inputs.source-branch }}

      - name: Set up git user
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          git config --global user.email "autoci@relaynetwork.com"
          git config --global user.name "Auto Release Agent"
      
      - name: Generate the Release Name
        id: generate-name
        env:
          INPUT_NAME: ${{inputs.release-name}}
        run: |
          export BRANCH_NAME=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          export RELEASE_NAME="${INPUT_NAME:-${BRANCH_NAME}}"
          echo "branch_name=${RELEASE_NAME}" >> $GITHUB_OUTPUT
     
      - name: Create Release Tag
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          RELEASE_NAME: ${{steps.generate-name.outputs.RELEASE_NAME}}
        run: |
          git tag $RELEASE_NAME
          git push origin --tags
          echo "release is $RELEASE_NAME"

      - name: Create Release
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          RELEASE_NAME: ${{steps.generate-name.outputs.branch_name}}
        working-directory: ./
        run: |
          gh release create $RELEASE_NAME -t $RELEASE_NAME --generate-notes --target ${{ github.sha }}
