name: Create a GitHub release

# Creates a release based on the Relay release requirements.
# 
# This action will generate a release name using the current date and the first
# 7 digits of the current commit SHA. This release name will be used to generate
# a new entry in the GitHub Release page, a new tag, and a new branch with the
# release named prefixed with `RELEASE-`.

on: workflow_dispatch

jobs:
  release:
    name: Create Release Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          fetch-depth: 0

      - name: Install auto
        run: npm install auto @auto-it/git-tag
      
      - name: Set up git user
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          git config --global user.email "autoci@relaynetwork.com"
          git config --global user.name "Auto Release Agent"
      
      - name: Set up parameters
        run: |
          export DATE=$(date '+%Y-%m-%d')
          export SUFFIX=1
          while git branch -r | grep -w "RELEASE-$DATE-$(printf '%02d' $SUFFIX)"
          do
            ((SUFFIX++)) 
          done
          export BRANCHNAME=RELEASE-$DATE-$(printf '%02d' $SUFFIX)
          echo "DATE=$DATE" >> $GITHUB_ENV
          echo "BRANCHNAME=$BRANCHNAME" >> $GITHUB_ENV
      
      - name: Cut Branch & Tag
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          BRANCHNAME: ${{env.BRANCHNAME}}
        run: |
          git checkout -b $BRANCHNAME
          git push -u origin $BRANCHNAME
          git tag $BRANCHNAME
          git push origin --tags

      - name: Create Release
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          BRANCHNAME: ${{env.BRANCHNAME}}
        working-directory: ./
        run: |
          npx -y auto release --no-version-prefix --use-version $BRANCHNAME
