name: Create Release Branch

# Creates a release based on the Relay release requirements.
# 
# This action will generate a release name using the current date and the first
# 7 digits of the current commit SHA. This release name will be used to generate
# a new entry in the GitHub Release page, a new tag, and a new branch with the
# release named prefixed with `RELEASE-`.

on: workflow_call

jobs:
  create-branch:
    name: Create Release Branch
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{steps.set-parameters.outputs.branch_name}}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          fetch-depth: 0

      - name: Install auto
        run: npm install auto @auto-it/git-tag
      
      - name: Set up git user
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          git config --global user.email "autoci@relaynetwork.com"
          git config --global user.name "Auto Release Agent"
      
      - name: Set up parameters
        id: set-parameters
        run: |
          export DATE=$(date '+%Y-%m-%d')
          export SUFFIX=1
          while git branch -r | grep -w "RELEASE-$DATE-$(printf '%02d' $SUFFIX)"
          do
            ((SUFFIX++)) 
          done
          export BRANCHNAME=RELEASE-$DATE-$(printf '%02d' $SUFFIX)
          echo "branch_name=${BRANCHNAME}" >> $GITHUB_OUTPUT
      
      - name: Cut Branch & Tag
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          BRANCH_NAME: ${{steps.set-parameters.outputs.branch_name}}
        run: |
          git checkout -b $BRANCH_NAME
          git push -u origin $BRANCH_NAME
  github-release:
    uses: ./.github/workflows/github-release.yml
    secrets: inherit
    needs: [create-branch]
    with:
      release-name: ${{needs.create-branch.outputs.branch_name}}
